"""
Causal model definitions for the task.
"""

from causalab.causal.causal_model import CausalModel, build_output_tokens
from causalab.causal.trace import Mechanism, input_var
from .templates import TEMPLATES, fill_template
from .config import TASK_NAME, FOOS, BARS

# For single-template tasks, use a module constant (NOT a causal variable).
# Only include template as an input_var when the task has multiple templates.
TEMPLATE = TEMPLATES[0]

# TODO: implement variables, values, parents, mechanisms
# the variables "raw_input" and "raw_output" should both be strings
# Some variables are conceptually best expressed as lists or tuples,
# but the causal model implementation requires separating these into
# individual scalar variables with _{i} suffixes (e.g., choice_0, choice_1).
# Avoid creating compound/aggregate variables.

values = {
    "foo": FOOS,
    "bar": BARS,
    "raw_input": None,  # Generated from template
    "raw_output": None,  # Generated by model
}

# Define mechanisms using the new Mechanism API
mechanisms = {
    # Input variables (no parents)
    "foo": input_var(FOOS),
    "bar": input_var(BARS),
    # Computed variables
    "raw_input": Mechanism(
        parents=["foo", "bar"],
        compute=lambda t: fill_template(TEMPLATE, t["foo"], t["bar"]),
    ),
    "raw_output": Mechanism(
        parents=["raw_input"],
        compute=lambda t: "",  # Placeholder - will be filled by model
    ),
}

# ``output_tokens`` declares, per value of the answer variable, the surface
# form(s) the model emits — the single source of truth for scoring. The resolver
# (``causalab.methods.output_tokens``) derives the probability-path score tokens
# from it, and ``derive_checker`` derives the string checker from it, so a task
# that declares ``output_tokens`` needs no ``checker.py`` (ship one only for a
# genuinely-custom matcher — it takes precedence over the derived checker).
# ``build_output_tokens`` makes the mechanical ``[" v", v]`` map; write the map
# explicitly for synonyms or a non-default surface form. Key it by the answer
# variable. For ``"prefix"`` matching (output continues past the answer) pass
# ``match_modes={"<answer_var>": "prefix"}``.
#
# TODO: key ``output_tokens`` by *your* answer variable (here illustrated with
# "bar") and set TARGET_VARIABLE to the variable steered/scored.
TARGET_VARIABLE = "bar"
output_tokens = {"bar": build_output_tokens(BARS)}

# The loader reads the canonical UPPER_SNAKE export ``CAUSAL_MODEL`` (singleton).
CAUSAL_MODEL = CausalModel(
    mechanisms, values, id=TASK_NAME, output_tokens=output_tokens
)
