"""Session-local analysis `{{ANALYSIS_NAME}}`.

Generated by the setup-analyses guide. See set_up_analysis.md alongside this file for the
spec; see docs/CODEBASE.md §3 for the layering rules this module respects.
"""

from .main import main

__all__ = ["main"]
