"""Numerical-tier golden tests for every golden runner.

Re-runs each ``tests/end_to_end/configs/golden/*.yaml`` under the seed
pinned in ``tests/end_to_end/goldens/<runner>.json``, then asserts
each captured value is within the per-key tolerance (or the JSON's
``"default"`` tolerance when no per-key override is set). Covers both the
baseline goldens (``mcqa``, ``weekdays``, ``entity_binding``) and the
analysis-chain goldens (``weekdays_output_manifold``, ``weekdays_pullback``)
— the latter pin extracted tensor reductions across the whole output tree
(see ``_helpers/golden.py::extract_values``), not just artifact existence.

Device follows the golden's pinned model fixture (``cfg.model.device``)
— see ``_helpers/golden.py``'s hardware contract for the per-tier
policy. Goldens are regenerated by
``tests/end_to_end/update_goldens.py``.

Failure mode is intentionally chatty — the assertion message names the
metric, the expected value, the actual value, and the tolerance, so a
drift caught by CI is one line of output away from a fix or a
regen-and-review-the-diff decision.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.end_to_end._helpers.golden import (
    Golden,
    enumerate_goldens,
    load_golden,
    run_baseline_for_golden,
)

pytestmark = pytest.mark.golden


def _golden_id(path: Path) -> str:
    """Pretty parametrize id: just the filename stem."""
    return path.stem


_GOLDEN_PATHS = enumerate_goldens()


@pytest.mark.parametrize(
    "golden_path",
    _GOLDEN_PATHS,
    ids=[_golden_id(p) for p in _GOLDEN_PATHS],
)
def test_baseline_golden(golden_path: Path, tmp_path: Path) -> None:
    """Re-run the baseline, assert every value is within tolerance."""
    golden: Golden = load_golden(golden_path)
    actual, _device = run_baseline_for_golden(golden, tmp_path)

    missing = sorted(set(golden.values) - set(actual))
    assert not missing, (
        f"[{golden.runner}] expected metrics not produced this run: "
        f"{missing}. Either update the golden via "
        f"tests/end_to_end/update_goldens.py or adjust "
        f"tests/end_to_end/_helpers/golden.py::extract_values."
    )

    for key, expected in golden.values.items():
        got = actual[key]
        if isinstance(expected, float) and isinstance(got, (int, float)):
            tol = golden.tol_for(key)
            assert abs(got - expected) <= tol, (
                f"[{golden.runner}] metric {key}: expected {expected!r} "
                f"within tolerance {tol!r}, got {got!r} "
                f"(diff={got - expected!r})"
            )
        else:
            # Non-float values (ints, strings, lists) compared exactly.
            # The most common non-float here is the safetensors SHA-256 —
            # which we treat as a soft signal: a hash mismatch only fails
            # if the runner is declared deterministic. Otherwise the
            # within-tolerance reductions (mean / std / first / last) do
            # the work.
            if key.endswith(".sha256") and not golden.deterministic:
                continue
            assert got == expected, (
                f"[{golden.runner}] metric {key}: expected {expected!r}, got {got!r}"
            )
