# @package _global_
defaults:
- /base
- /task: hierarchical_equality
- /model: llama31_8b
- /analysis/locate
- /analysis/subspace
- _self_
task:
  n_train: 100
  n_test: 50
  target_variables:
  - left_equality
  - right_equality
  - result_equality

post:
- type: variable_localization_heatmap
  source_step: locate
  source_method: interchange
locate:
  layers: [10, 20]
subspace:
  method: pca
  k_features: 8

