# @package _global_
defaults:
- /base
- /task: hierarchical_equality
- /model: llama31_8b
- /analysis/locate
- _self_
task:
  target_variables:
  - left_equality
  - right_equality
  - result_equality


post:
- type: variable_localization_heatmap
  source_step: locate
  source_method: interchange
  title: "HE Variable Localization"
locate:
  layers: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
