"""Session-local method `{{METHOD_NAME}}`.

Generated by the setup-methods guide. See set_up_method.md alongside this file for the
spec; see docs/CODEBASE.md §3 for the layering rules this module respects.
"""

from .{{METHOD_NAME}} import {{METHOD_NAME}}

__all__ = ["{{METHOD_NAME}}"]
