# @package _global_
defaults:
- /base
- /task: natural_domains_arithmetic_weekdays
- /model: llama31_8b
# - /analysis/baseline
# - /analysis/locate
# - /analysis/subspace
# - /analysis/activation_manifold
# - /analysis/output_manifold
- /analysis/path_steering
# - /analysis/pullback
- _self_

task:
  target_variable: result

locate:
  layers: [28]

subspace:
  layers: [28]

activation_manifold:
  layers: [28]

path_steering:
  replot_only: true
  selected_pairs:
    - ["Monday", "Thursday"]
  num_steps_along_path: 300

  path_visualization:
    colored_concepts_in_legend: [
      "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
    ]
    figsize: [6, 4.5]

pullback:
  selected_pairs:
    - ["Monday", "Thursday"]
  embedding_optim:
    n_steps: 50
    k_opt: [8, 16, 32, 64]