# @package _global_
defaults:
- /base
- /task: MCQA
- /model: llama31_8b
- /analysis/locate
- _self_
task:
  target_variables:
  - answer
  - answer_position
  n_train: 64
  n_test: 16

locate:
  layers: [0, 2, 4, 6, 8, 10]
  n_steer: 16
